const test = require('node:test');
const assert = require('node:assert/strict');
const {CodexController} = require('../mini_program/utils/codex/controller');
const {clone, buildLibrary, defaultPreferences, effectiveSettings, pathKey} = require('../mini_program/utils/codex/model');
const {ReadScope, ContentReader, readThread, findBeginning, newBeginning, mergeHistory} = require('../mini_program/utils/codex/history');
const {projectConversation, conversationWindow} = require('../mini_program/utils/codex/conversation');
const {approvalResult} = require('../mini_program/utils/codex/approvals');
const {ResourceBrowser, ImageCache} = require('../mini_program/utils/codex/resources');
const root = 'C:\\Fixture\\LanPower';
const tick = () => new Promise(resolve => setImmediate(resolve));
const turn = (id, text = id) => ({id, status:'completed', items:[{id:id+'-u',type:'userMessage',content:[{type:'text',text:'任务 '+text}]},{id:id+'-a',type:'agentMessage',text:'回复 '+text,phase:'final_answer'}]});
class Runtime {
  constructor() {
    this.calls=[];this.overrides={};this.queue=[];this.revision=1;this.active=[];this.approvals=[];
    this.threads=[{id:'a',name:'聊天 A',cwd:root,control:'remote',model:'m-a',reasoningEffort:'medium',collaborationMode:'default',turns:[turn('old')]},{id:'b',name:'聊天 B',cwd:root,control:'remote',model:'m-b',reasoningEffort:'high',turns:[turn('b-old')]}];
  }
  async request(method,params={},scope) {
    if(scope)scope.check();this.calls.push({method,params:clone(params)});if(this.overrides[method])return this.overrides[method](params,scope);
    const thread=this.threads.find(row=>row.id===params.threadId);
    if(method==='lanpower/status')return {sharedControl:true,desktopControl:true,queueSupported:true,chatSupported:true,submissionReceipts:true,loggedIn:true,projects:[{name:'LanPower',path:root}],activeTurns:this.active,pendingApprovals:this.approvals,lanpowerRevision:this.revision,library:{revision:1,preferences:defaultPreferences()}};
    if(method==='model/list')return {data:[{id:'m-a',isDefault:true,supportedReasoningEfforts:[{reasoningEffort:'medium'},{reasoningEffort:'high'}],defaultReasoningEffort:'medium'},{id:'m-b',supportedReasoningEfforts:[{reasoningEffort:'high'}],defaultReasoningEffort:'high'}]};
    if(method==='collaborationMode/list')return {data:[{mode:'plan'}]};
    if(method==='thread/list')return {data:this.threads.map(row=>({...row,turns:undefined})),nextCursor:null};
    if(method==='thread/read')return {thread:clone({...thread,lanpowerRevision:this.revision})};
    if(method==='thread/queue/list')return {data:clone(this.queue),nextCursor:null};
    if(method==='turn/start'){const next={id:'new',status:'inProgress',items:[{id:'new-user',type:'userMessage',content:params.input}]};thread.turns.push(next);this.active=[{threadId:thread.id,turnId:next.id}];return {turn:next};}
    if(method==='turn/steer')return {turnId:params.expectedTurnId};
    if(method==='turn/interrupt'){this.active=[];thread.turns.at(-1).status='interrupted';return {};}
    if(method==='thread/queue/add'){this.queue.push({id:params.clientUserMessageId,input:params.input});return {};}
    if(method==='thread/queue/update'){this.queue.find(row=>row.id===params.queuedSubmissionId).input=params.input;return {};}
    if(method==='thread/queue/delete'){this.queue=this.queue.filter(row=>row.id!==params.queuedSubmissionId);return {};}
    if(method==='thread/queue/start'){this.queue=this.queue.filter(row=>row.id!==params.queuedSubmissionId);return {};}
    if(method==='thread/queue/reorder'){this.queue=params.queuedSubmissionIds.map(id=>this.queue.find(row=>row.id===id));return {};}
    if(method==='thread/start'||method==='lanpower/chat/start'){const value={id:'created',name:'新聊天',cwd:params.cwd||'',isChat:!params.cwd,control:'remote',turns:[]};this.threads.push(value);return {thread:value};}
    if(method==='thread/name/set'){thread.name=params.name;return {};}
    if(method==='thread/fork'){const value=clone({...thread,id:'forked'});this.threads.push(value);return {thread:value};}
    if(method==='thread/rollback'){thread.turns.splice(-params.numTurns);return {thread:clone(thread)};}
    if(method==='thread/archive'||method==='thread/unarchive')return {};
    if(method==='lanpower/library/update')return {revision:params.revision+1,preferences:params.preferences};
    if(method==='lanpower/submission/read')return {state:'accepted'};
    if(method==='thread/resume')return {};
    throw new Error('测试未提供接口 '+method);
  }
  async paceHistory(scope){if(scope)scope.check();}
  connect(){}
  stop(){}
  reconcileApprovals(){}
  async decide(id,result){this.calls.push({method:'decide',params:{id,result}});this.approvals=this.approvals.filter(row=>row.id!==id);}
}
async function setup(t){const runtime=new Runtime(),c=new CodexController(runtime);t.after(()=>c.dispose());c.deviceId='pc-a';c.state='runtime_ready';await c.restore();await c.selectThread('a');return {c,runtime};}
test('恢复原窗口模型、思考强度、计划能力与项目',async t=>{const {c}=await setup(t);assert.equal(c.canControl,true);assert.deepEqual(effectiveSettings(c.threadSettings),{model:'m-a',effort:'medium',mode:'default'});assert.equal(c.planSupported,true);assert.equal(c.projects[0].path,root);});
test('未发送参数不被轮询覆盖，成功发送后恢复继承',async t=>{const {c,runtime}=await setup(t);c.chooseSetting('model','m-b');c.chooseSetting('mode','plan');await c.refreshCurrent();assert.equal(effectiveSettings(c.threadSettings).model,'m-b');c.input('开始任务');await c.submit();const call=runtime.calls.find(row=>row.method==='turn/start');assert.equal(call.params.model,'m-b');assert.equal(call.params.effort,'high');assert.equal(call.params.mode,'plan');assert.equal(c.receipt.state,'accepted');assert.deepEqual(c.threadSettings.overrides,{});});
test('不同聊天和电脑隔离草稿、附件与参数',async t=>{const {c}=await setup(t);c.input('A 的草稿');c.addFile(root+'\\README.md');c.addSkill({name:'check',path:root+'\\skill'});c.chooseSetting('mode','plan');await c.selectThread('b');c.input('B 的草稿');assert.equal(c.draft.files.length,0);await c.selectThread('a');assert.equal(c.draft.text,'A 的草稿');assert.equal(c.draft.files.length,1);assert.equal(effectiveSettings(c.threadSettings).mode,'plan');c.chooseDevice('pc-b');assert.equal(c.draft.text,'');assert.equal(c.current,null);assert.equal(c.threads.length,0);});
test('失去确认的提交冻结输入，恢复只查询回执',async t=>{const {c,runtime}=await setup(t);runtime.overrides['turn/start']=async()=>{throw Object.assign(new Error('连接丢失'),{code:'CONNECTION',uncertain:true});};c.input('只能发送一次');await c.submit();assert.equal(c.receipt.state,'uncertain');assert.equal(c.sendBlocked,true);await c.submit();assert.equal(runtime.calls.filter(row=>row.method==='turn/start').length,1);c.onState('disconnected');c.state='runtime_ready';await c.restore();assert.equal(c.receipt.state,'accepted');assert.equal(runtime.calls.filter(row=>row.method==='turn/start').length,1);});
test('明确拒绝恢复文字、文件、技能和图片草稿',async t=>{const {c,runtime}=await setup(t);runtime.overrides['turn/start']=async()=>{throw Object.assign(new Error('拒绝'),{uncertain:false});};c.input('保存输入');c.addFile(root+'\\README.md');c.addSkill({name:'check',path:root+'\\skill'});c.draft.images.push({url:'data:image/png;base64,YQ==',src:'temp.png'});await c.submit();assert.equal(c.receipt.state,'failed');assert.equal(c.draft.text,'保存输入');assert.equal(c.draft.files.length,1);assert.equal(c.draft.skills.length,1);assert.equal(c.draft.images.length,1);});
test('运行中明确选择排队或引导，避免重新启动任务',async t=>{const {c,runtime}=await setup(t);c.activeTurns.set('a','running');runtime.active=[{threadId:'a',turnId:'running'}];c.chooseSetting('model','m-b');c.input('排队任务');await c.submit('queue');assert.equal(c.queue.length,1);const queued=runtime.calls.find(row=>row.method==='thread/queue/add');assert.ok(queued.params.submissionId);assert.ok(!('model'in queued.params));c.input('改当前任务');await c.submit('steer');assert.equal(runtime.calls.find(row=>row.method==='turn/steer').params.expectedTurnId,'running');assert.equal(runtime.calls.filter(row=>row.method==='turn/start').length,0);});
test('编辑排队消息保留原生文件、技能、图片结构，支持排序与删除',async t=>{const {c,runtime}=await setup(t);runtime.queue=[{id:'q1',input:[{type:'text',text:'# Files mentioned by the user:\n## README.md: C:/Fixture/README.md\n\n## My request for Codex:\n检查文件'},{type:'skill',name:'check',path:'C:/Fixture/skill'},{type:'image',url:'data:image/png;base64,YQ=='}]},{id:'q2',input:[{type:'text',text:'第二条'}]}];await c.refreshQueue();c.editQueue('q1');assert.equal(c.draft.text,'检查文件');assert.equal(c.draft.skills.length,1);assert.equal(c.draft.files.length,1);assert.equal(c.draft.images.length,1);c.input('修改后的要求');await c.submit();assert.equal(runtime.calls.find(row=>row.method==='thread/queue/update').params.input[1].type,'image');assert.equal(runtime.queue[0].input[2].type,'skill');await c.queueAction('reorder','q2',-1);assert.equal(c.queue[0].id,'q2');await c.queueAction('delete','q1');assert.equal(c.queue.length,1);await c.queueAction('start','q2');assert.equal(c.queue.length,0);});
test('晚到的读取结果不覆盖实时新任务',async t=>{const {c,runtime}=await setup(t);let release;runtime.overrides['thread/read']=()=>new Promise(resolve=>{release=()=>resolve({thread:clone({...runtime.threads[0],lanpowerRevision:1})});});const syncing=c.refreshCurrent();await tick();c.onEvent({method:'turn/started',params:{threadId:'a',lanpowerRevision:2,turn:{id:'new-live',status:'inProgress',items:[]}}});release();await syncing;assert.equal(c.activeTurn,'new-live');assert.ok(c.current.turns.some(turn=>turn.id==='new-live'));});
test('旧任务结束通知不停止较新的活动任务',async t=>{const {c}=await setup(t);c.activeTurns.set('a','newer');c.onEvent({method:'turn/completed',params:{threadId:'a',lanpowerRevision:2,turn:{id:'older',status:'completed',items:[]}}});assert.equal(c.activeTurn,'newer');});
test('旧电脑的延迟响应不能渗入新电脑',async t=>{const {c,runtime}=await setup(t);let release;runtime.overrides['thread/read']=()=>new Promise(resolve=>{release=()=>resolve({thread:clone(runtime.threads[1])});});const read=c.selectThread('b');await tick();c.chooseDevice('pc-b');release();await read;assert.equal(c.current,null);assert.equal(c.threadId,'');assert.equal(c.messages().messages.length,0);});
test('后台清空审批和控制，保留未发草稿且不重发',async t=>{const {c,runtime}=await setup(t);c.input('尚未发送');c.approvals.set('1',{id:1,method:'item/fileChange/requestApproval',params:{threadId:'a'}});c.onState('disconnected');assert.equal(c.canControl,false);assert.equal(c.approvals.size,0);assert.equal(c.draft.text,'尚未发送');c.state='runtime_ready';await c.restore();assert.equal(c.draft.text,'尚未发送');assert.equal(runtime.calls.filter(row=>row.method==='turn/start').length,0);});
test('状态恢复失败时保留缓存但不开放控制',async t=>{const {c,runtime}=await setup(t);c.onState('disconnected');runtime.overrides['lanpower/status']=async()=>{throw new Error('无法读取原窗口');};c.state='runtime_ready';await c.restore();assert.ok(c.current);assert.equal(c.canControl,false);assert.equal(c.recovering,false);});
test('桌面只读与未完成恢复时不允许发送或停止',async t=>{const {c,runtime}=await setup(t);c.sharedControl=false;c.current.control='desktop';c.input('只读');await c.submit();assert.equal(c.canControl,false);assert.equal(runtime.calls.some(row=>row.method==='turn/start'),false);c.sharedControl=true;c.recovering=true;assert.equal(c.canControl,false);});
test('模型与历史接口按能力分页，过大历史自动减小范围',async()=>{const limits=[],client={paceHistory:async()=>{},request:async(method,params)=>{limits.push(params.historyLimit);if(params.historyLimit>2)throw Object.assign(new Error(),{code:'result_too_large'});return {thread:{id:'a'}};}};assert.equal((await readThread(client,'a',new ReadScope())).thread.id,'a');assert.deepEqual(limits,[8,4,2]);});
test('大量聊天分页不再在 200 条截断',async t=>{const {c,runtime}=await setup(t);c.threads=[];runtime.overrides['thread/list']=async params=>{const page=Number(params.cursor||0);return {data:Array.from({length:50},(_,index)=>({id:String(page*50+index),name:'任务',cwd:root})),nextCursor:page<5?String(page+1):null};};await c.loadThreads();for(let index=0;index<5;index++)await c.loadThreads(true);assert.equal(c.threads.length,300);assert.equal(c.listCursor,'');});
test('同名项目依完整路径归属，保留空项目和独立聊天',()=>{const prefs=defaultPreferences(),result=buildLibrary([{name:'同名',path:'C:/Work/X'},{name:'同名',path:'D:/Work/X'},{name:'空项目',path:'D:/Empty'}],[{id:'a',cwd:'c:\\work\\x\\sub',name:'A'},{id:'b',cwd:'D:/Work/X',name:'B'},{id:'chat',cwd:'',isChat:true,name:'独立'}],prefs);assert.equal(result.projects.length,3);assert.equal(result.projects.find(row=>row.path==='C:/Work/X').threads[0].id,'a');assert.equal(result.chats.length,1);assert.equal(pathKey('\\\\?\\C:\\Work\\X'),'c:/work/x');});
test('项目收纳、置顶、排序、展开状态通过电脑端版本更新',async t=>{const {c,runtime}=await setup(t);c.changeLibrary('pinned','a');c.changeLibrary('collapsed',pathKey(root));c.changeLibrary('sort','','created');c.changeLibrary('chatsFirst','',true);await c.flushLibrary();const call=runtime.calls.find(row=>row.method==='lanpower/library/update');assert.equal(call.params.revision,1);assert.deepEqual(call.params.preferences.pinned,['a']);assert.equal(call.params.preferences.chatsFirst,true);assert.equal(c.library.revision,2);});
test('原生重命名、分支、回退、归档、恢复和独立聊天',async t=>{const {c,runtime}=await setup(t);await c.threadAction('rename','新名字');assert.equal(c.current.name,'新名字');await c.threadAction('fork');assert.equal(c.threadId,'forked');c.current.turns.push(turn('rollback'));runtime.threads.find(row=>row.id==='forked').turns.push(turn('rollback'));await c.threadAction('rollback','rollback');assert.equal(c.current.turns.length,1);await c.threadAction('archive');assert.equal(c.threadId,'');const id=await c.createThread('',true);assert.equal(id,'created');assert.equal(c.current.isChat,true);await c.toggleArchived();await c.selectThread('a');assert.equal(c.canControl,false);await c.threadAction('unarchive');assert.equal(c.threadId,'');});
test('逐条审批只发一次，服务端状态恢复后才解除等待',async t=>{const {c,runtime}=await setup(t);c.activeTurns.set('a','live');const request={id:'approval',method:'item/fileChange/requestApproval',params:{threadId:'a',turnId:'live'}};runtime.approvals=[request];c.approvals.set(JSON.stringify(request.id),request);await Promise.all([c.decide(JSON.stringify(request.id),true),c.decide(JSON.stringify(request.id),true)]);assert.equal(runtime.calls.filter(row=>row.method==='decide').length,1);assert.deepEqual(runtime.calls.find(row=>row.method==='decide').params.result,{decision:'accept'});});
test('问题支持选项、补充、多选并发送原生答案',()=>{const request={method:'item/tool/requestUserInput',params:{questions:[{id:'mode',options:[{label:'A'},{label:'B'}],multiSelect:true},{id:'note'}]}};const result=approvalResult(request,true,{mode:{selected:[0,1],text:'附加'},note:{text:'说明'}});assert.deepEqual(result.answers.mode.answers,['A','B','附加']);assert.deepEqual(result.answers.note.answers,['说明']);assert.throws(()=>approvalResult(request,true,{}),/每个问题/);});
test('网络授权只限本任务，不接受扩大权限；MCP授权按网页边界在电脑处理',()=>{assert.deepEqual(approvalResult({method:'item/permissions/requestApproval',params:{permissions:{network:{enabled:true}}}},true,{}),{permissions:{network:{enabled:true}},scope:'turn'});assert.throws(()=>approvalResult({method:'item/permissions/requestApproval',params:{permissions:{fileSystem:{}}}},true,{}),/原窗口/);assert.deepEqual(approvalResult({method:'mcpServer/elicitation/request',params:{}},false,{}),{action:'decline',content:null});});
test('完整历史定位可取消并接续，游标循环明确失败',async()=>{const scope=new ReadScope(),job=newBeginning();let calls=0;const client={paceHistory:async()=>{},request:async(method,params)=>{calls++;return {data:[turn(params.cursor||'latest')],nextCursor:params.cursor==='older'?null:'older'};}};await assert.rejects(findBeginning(client,'a',job,scope,()=>scope.cancel()),{code:'CANCELLED'});assert.equal(job.count,1);await findBeginning(client,'a',job,new ReadScope());assert.equal(calls,2);assert.equal(job.count,2);assert.equal(job.complete,true);const cyclic={paceHistory:async()=>{},request:async()=>({data:[],nextCursor:'same'})};await assert.rejects(findBeginning(cyclic,'a',newBeginning(),new ReadScope()),/未推进/);});
test('超大 Unicode 内容分段恢复，保留全文并拒绝串项',async()=>{const item={id:'big',type:'commandExecution',aggregatedOutput:'完整内容🎨'.repeat(80000)},body=JSON.stringify(item),placeholder={id:'big',type:'lanpowerLargeItem',reference:'ref',originalType:'commandExecution',characters:body.length};const client={paceHistory:async()=>{},request:async(method,params)=>{const data=body.slice(params.offset,params.offset+16000);return {offset:params.offset,data,characters:body.length,nextOffset:params.offset+data.length===body.length?null:params.offset+data.length};}};const reader=new ContentReader('a');await reader.read(client,placeholder,new ReadScope());assert.equal(reader.apply([{id:'t',items:[placeholder]}])[0].items[0].aggregatedOutput,item.aggregatedOutput);const broken={...client,request:async()=>({offset:1,data:'x',characters:body.length,nextOffset:2})};await assert.rejects(new ContentReader('a').read(broken,placeholder,new ReadScope()),/不连续/);});
test('窗口投影不删除原始历史或长正文，完整内容仍可访问',()=>{const turns=Array.from({length:180},(_,index)=>turn(String(index),'中文🎨'.repeat(3000))),source={turns},rows=projectConversation(source),before=JSON.stringify(source),view=conversationWindow(rows);assert.ok(view.messages.length<=36);assert.ok(Buffer.byteLength(JSON.stringify(view))<1048576);assert.equal(view.hasWindowBefore,true);assert.equal(JSON.stringify(source),before);assert.ok(view.messages.some(row=>row.hasMoreText));assert.equal(mergeHistory([turn('1'),turn('2')],[turn('2'),turn('3')]).length,3);});
test('工作过程、命令、文件分组不影响最终回复和完整内容',()=>{const value={id:'t',status:'completed',items:[{id:'u',type:'userMessage',content:[{type:'text',text:'任务'}]},{id:'commentary',type:'agentMessage',phase:'commentary',text:'处理中'},{id:'cmd',type:'commandExecution',command:'check',aggregatedOutput:'完整输出'},{id:'file',type:'fileChange',changes:[{path:'x.js',diff:'-old\n+new'}]},{id:'final',type:'agentMessage',phase:'final_answer',text:'完成'}]};assert.ok(!projectConversation({turns:[value]}).some(row=>row.itemId==='commentary'));const rows=projectConversation({turns:[value]},new Set(['t']),new Set(['activity:t:cmd']));assert.equal(rows.filter(row=>row.kind==='activity').length,2);assert.equal(rows.find(row=>row.itemId==='cmd').text,'完整输出');assert.equal(rows.find(row=>row.itemId==='file').files[0].diff,'-old\n+new');});
test('文件浏览、搜索、预览和技能目录使用目标电脑接口且隔离旧结果',async()=>{const calls=[],client={request:async(method,params)=>{calls.push({method,params});if(method==='lanpower/files/read')return {path:'README.md',content:'正文'.repeat(9000)};if(method==='skills/list')return {data:[{skills:[{name:'skill',path:'x',enabled:true}]}]};return {data:[{name:'README.md',path:'README.md'}],nextCursor:null};}};const resource=new ResourceBrowser(client,()=>true,()=>{});await resource.open(root);await resource.search('README');await resource.files('lanpower/files/read',{path:'README.md'});assert.equal(resource.fileView().selected.hasMore,true);assert.ok(resource.state.selected.content.length>8000);await resource.directoryCatalog('skill',root);assert.equal(resource.catalog.rows[0].name,'skill');assert.ok(calls.every(call=>call.params.cwd===root));let release;client.request=()=>new Promise(resolve=>release=resolve);const old=resource.directory('.');resource.reset();release({data:[{name:'secret'}]});await old;assert.equal(resource.state.files.length,0);});
test('图片认证读取使用会话，临时图片在清理时删除',async()=>{const calls=[],deleted=[],wxApi={env:{USER_DATA_PATH:'/tmp/fixture'},base64ToArrayBuffer:value=>Uint8Array.from(Buffer.from(value,'base64')).buffer,getFileSystemManager:()=>({writeFile:options=>options.success(),unlink:options=>deleted.push(options.filePath)})},client={request:async(method,params)=>{calls.push({method,params});return {contentType:'image/png',base64:'YQ==',size:1};}};const cache=new ImageCache(wxApi,client);const path=await cache.resolve(root+'\\image.png','a',root);assert.equal(calls[0].params.threadId,'a');assert.equal(calls[0].method,'lanpower/image/read');assert.ok(path.includes('codex-preview'));cache.clear();assert.equal(deleted.length,1);});
